apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: green
  name: green
  namespace: green-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  strategy: {}
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - image: DOCKER
        name: green
        ports:
        - containerPort: 8080
        resources: {}
status: {}
